export default {
  CREATE_USER:"CREATE_USER",
  DELETE_USER:"DELETE_USER",
  CREATE_TOKEN:"CREATE_TOKEN",
  ON_NOTIFICATIONS:"ON_NOTIFICATIONS",
  REMOVE_NOTIFICATIONS: "REMOVE_NOTIFICATIONS",
  SIGN_OUT: "SIGN_OUT",
};